### ISSUE TITLE
Long name of option is different in help text

### ISSUE THREAD

**Issue by BBBSnowball** [erikarvstedt/extra-container#10]
The help text says `--update-changed` (see [line 33](https://github.com/erikarvstedt/extra-container/blob/master/extra-container#L33)) but the code uses `--update` (see [line 272](https://github.com/erikarvstedt/extra-container/blob/master/extra-container#L272)). The same goes for `--restart-changed` vs. `--restart`.

As there isn't any error for unrecognized options, I didn't notice that I was using the wrong options. After a day, I noticed that using the short option does work.

Can we add an error message for unrecognized options? If my understanding is correct, we are adding all the unrecognized options via `set` but we are only ever using `$1`. Can we error out if `$args` has more than one item? Can we complain about any arguments that start with a minus but are not one of the recognized arguments? Maybe both?

I can create a pull request for this. Just tell me which of my suggestions we should apply.

**Comment by erikarvstedt** [comment]
Fixed in release `0.5`.
