### ISSUE TITLE
Upstream package in nixpkgs

### ISSUE THREAD

**Issue by Lassulus** [erikarvstedt/extra-container#13]
would be nice to add the package in nixpkgs? So people don't have to depend on IFD to activate this.

**Comment by erikarvstedt** [comment]
I've just created nixpkgs PR [`extra-container: init at 0.5`](https://github.com/NixOS/nixpkgs/pull/102354).

**Comment by deliciouslytyped** [comment]
It would be nice if the PR could be finished?
