### ISSUE TITLE
Flake support

### ISSUE THREAD

**Issue by tgunnoe** [erikarvstedt/extra-container#19]
Is there a way we can add flake support in an effort to streamline the reproducibility of extra-container? Ideally I see 2 types of outputs from this repository: NixOS and Non-NixOS with systemd.

I am currently using this in a flake with 
```
inputs.extra-container-src = {
      url = github:erikarvstedt/extra-container;
      flake = false;
    };
```
I then add that to pkgs with callPackage
but then upon launching i have to add another input to an older nixpkgs revision for the `--nixpkgs-path` for launching extra-container. 

Then I was looking on this working with flakes on a non-nixos systemd install, but this is where I get lost, because there's a lot of references to `NIX_PATH`, channels, sudoers etc within the `util/`.  It would be good to abstract that directory using a flake output that does it for you. 

So I think it would be ideal to streamline this for users, have the flake offer up 2 outputs for each system type.

**Comment by erikarvstedt** [comment]
Fixed by https://github.com/erikarvstedt/extra-container/commit/93f72a85c35bc60ba871fe47762f79cc64160bf6.
