### ISSUE TITLE
extra-container broke on nixos-unstable

### ISSUE THREAD

**Issue by martinetd** [erikarvstedt/extra-container#26]
Hello,

I was reported in https://github.com/NixOS/nixpkgs/pull/159187 that I apparently broke extra-container: you're handpicking a few modules directly, in particular systemd's, and I've added dependencies to services.logrotate and users.groups.utmp by moving the logrotate configuration there (as it's a generated by systemd)

It would probably be possible to just satisfy these dependencies but I guess that'll slow your evaluation down a bit, and you probably don't want that?
I'd personally slightly prefer to keep the utmp/wtmp logrotate rules in a systemd-related file (doesn't really make sense given we depend on systemd for everything in nixos, but conceptually it should be possible to run logrotate without these two in a systemdless system...)...
I tried various variants of mkIf to make this bit easily skippable, which ought to work as the bits wouldn't be evaluated, but wasn't able to get this to work -- if you have an idea I'd be glad to follow it up. Otherwise I guess we can move it back or add a new separate module just for it...

```
$ extra-container shell -E "$container" 
Building containers...
error: attribute 'utmp' missing

       at /nix/store/1gzq5mbv5djgyf0f4ki0h7dfx36nbc98-source/nixos/modules/system/boot/systemd.nix:1225:31:

         1224|         rotate = 1;
         1225|         create = "0660 root ${config.users.groups.utmp.name}";
             |                               ^
         1226|         minsize = "1M";
(use '--show-trace' to show detailed location information)
```

**Comment by aanderse** [comment]
ping @erikarvstedt for opinion :heart:

**Comment by erikarvstedt** [comment]
Fixed in https://github.com/erikarvstedt/extra-container/commit/bdfd2bd3bcae53357e79f6ed023c6227de93cbcb.
Note that this requires this [nixpkgs commit](https://github.com/erikarvstedt/nixpkgs/commit/63528cb1a6183fceb4f18ca1b74617eca8dd67a1) which is currently only available in nixpkgs `master`.

**Comment by aanderse** [comment]
Thanks @erikarvstedt :heart:
