### ISSUE TITLE
Container start/stop scripts (host side)

### ISSUE THREAD

**Issue by milabs** [erikarvstedt/extra-container#32]
Hello,

It would be nice to have the ability to add start/stop commands for the container, executed on the host side.

For example, in a project I've working on I have to add some `iptables` rules once container started.

**Comment by erikarvstedt** [comment]
This can be achieved like so:
```nix
{
  containers.demo = {
    config = ...;
  };

  # Commands executed on the host
  systemd.services."container@demo" = {
    preStart = "...";
    postStart = "...";
    preStop = "...";
    postStop = "...";
  };
}
```

This pattern is used internally by `extra-container`, e.g. for [implementing `enableWAN`](https://github.com/erikarvstedt/extra-container/blob/9a594f75cc782c481df9d108624409d429a23f19/eval-config.nix#L226).

**Comment by milabs** [comment]
Wow, thanks. Haven't found that by myself.
