### ISSUE TITLE
"error: attribute 'fsPackages' missing" when building a container based on NixOS > 23.05

### ISSUE THREAD

**Issue by cillianderoiste** [erikarvstedt/extra-container#35]
I have some containers defined with flakes and when I try to build them (`nix run . -- create --start`) I get the error below, although they do work fine with inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";

I guess it's related to this change in nixpkgs: https://github.com/NixOS/nixpkgs/commit/c3fa4f91707f5b007539f9ce5fd0319cc2f6db66

```error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'container'
         whose name attribute is located at /nix/store/f0ddmw6s86y567yg06h5019z72szbzch-source/pkgs/stdenv/generic/make-derivation.nix:331:7

       … while evaluating attribute 'buildCommand' of derivation 'container'

         at /nix/store/a6w17dprk0d9pic7k6vy513rrryw0xyh-source/flake.nix:34:13:

           33|             name = "container";
           34|             buildCommand = old.buildCommand + "\n" + ''
             |             ^
           35|                 install -D -m700 <(

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'fsPackages' missing

       at /nix/store/f0ddmw6s86y567yg06h5019z72szbzch-source/nixos/modules/system/boot/systemd.nix:640:68:

          639|     systemd.services."systemd-fsck@".restartIfChanged = false;
          640|     systemd.services."systemd-fsck@".path = [ pkgs.util-linux ] ++ config.system.fsPackages;
             |                                                                    ^
          641|     systemd.services."systemd-makefs@" = {
```

**Comment by erikarvstedt** [comment]
I can't reproduce this with `nixos-24.05` or `nixpkgs-unstable`.
E.g., `nix build ./examples/flake`, which uses `nixpkgs-unstable` works fine.
Can you share a way to reproduce the error?

**Comment by cillianderoiste** [comment]
Thanks for checking. I see that if I change the container name, then the flake works as expected, but I don't know how to reproduce the error from scratch.
I tried creating a demo container, as in examples/flake except with nixos-23.05, and then afterwards upgrading it to nixos-24.05. This wasn't enough to trigger the error. 
At least now I know how to work around it. I'll close this ticket, but if you're curious and would like to debug further, or would like extra information, please let me know. Thanks again!
