### ISSUE TITLE
Flake usage requires extra-container to be in $PATH

### ISSUE THREAD

**Issue by edanaher** [erikarvstedt/extra-container#36]
Using the flake "installation", I was getting failures trying to `nix run . -- create --start` with the demo flake:
```bash
$ nix run . -- create --start                                                                     
/nix/store/r6fi1s1hn38dlvjdarg3qzhw7iyhddrm-container/bin/container: line 2: exec: extra-container: not found
```
Sure enough, that wrapper script is attempting to call the `extra-container` script with no path:
```bash
$ cat /nix/store/r6fi1s1hn38dlvjdarg3qzhw7iyhddrm-container/bin/container                         
#!/usr/bin/env bash                                                                                                                           
EXTRA_CONTAINER_ETC=/nix/store/r6fi1s1hn38dlvjdarg3qzhw7iyhddrm-container exec extra-container "$@"
```
A quick workaround was to install extra-container in my NixOS configuration (I suppose I could probably also have manually set $PATH).  But it seems like an odd oversight that this isn't using the standard nix full path; I'd expect the flake to install its own copy of extra-container and use that path, not depend on an external one.

**Comment by erikarvstedt** [comment]
The reason for the wrapper not bundling the `extra-container` binary is that `extra-container` requires a specific [installation process](https://github.com/erikarvstedt/extra-container?tab=readme-ov-file#install) on all compatible platforms (except for very old NixOS versions).
This means that `extra-container` requires system changes beyond installing a binary.

I could add a error message to the wrapper that points to the installation instructions. Would this have helped in your case?

**Comment by edanaher** [comment]
Ah, that makes sense.  I got a workaround quickly enough that it didn't really inconvenience me; I just thought it odd that a flake requires outside configuration.  But I see now that it takes a bit of extra work, so that makes sense.

I'd appreciate an explicit error message that makes it clear that the flake isn't quite standalone, but it's not a huge deal if you've got other priorities.

**Comment by erikarvstedt** [comment]
The container runner now prints a helpful error message: https://github.com/erikarvstedt/extra-container/commit/fa723fb67201c1b4610fd3d608681da362f800eb.

Thanks for bringing up this issue!

**Comment by edanaher** [comment]
Thank you for the quick explanation and fix!
