### ISSUE TITLE
`autoStart` option doesn't work

### ISSUE THREAD

**Issue by danbst** [erikarvstedt/extra-container#5]
On NixOS it is handled by setting extra symlinks in `/etc/systemd/system/machines.target.wants` directory. Currently I'm doing workaround of:
```
        machines_wants=/etc/systemd/system/machines.target.wants
        mkdir -p $machines_wants
        rm -rf $machines_wants/*
        for service in $(ls -d /usr/lib/systemd/system/*); do
          ln -s $service $machines_wants/
        done
```

**Comment by erikarvstedt** [comment]
Thanks for the suggestion, I'll fix that soon.

**Comment by erikarvstedt** [comment]
Implemented in https://github.com/erikarvstedt/extra-container/commit/8f729fcbb4deccb0a588f1ec2fdb01785b4f0059.
