### ISSUE TITLE
reload command missing

### ISSUE THREAD

**Issue by danbst** [erikarvstedt/extra-container#6]
It is supported by `nixos-container`

**Comment by erikarvstedt** [comment]
You mean `update`?
If you want to update your container, just run `extra-container create --start` with your updated config.

**Comment by erikarvstedt** [comment]
I've just [added support](https://github.com/erikarvstedt/extra-container/commit/5875a977636d87f6eee8383b35b07cbc2e6612fe) for updating running containers. Thanks for the suggestion!
